Enhance navbar modified style.css #132
garg3133/JagratiWebApp pull request #144
Opened 2021-03-11 11:41 UTC by Kritikaagra

2021-03-13 03:46 UTC, tmo66 requested changes
Make all these necessary changes.

2021-03-13 03:46 UTC, tmo66 commented on static/home/css/style.css
> +	transition: 0.4s ease;
Don't change Global Variables.

2021-03-13 03:46 UTC, tmo66 commented on static/home/css/style.css
> +.navbar a:hover{
Don't make changes here, do these changes in `navbar a: hover`.

2021-03-13 03:46 UTC, tmo66 commented on static/home/css/style.css
> +  }
Don't add extra whitespace and an extra line.

2021-03-13 03:46 UTC, tmo66 commented on static/home/css/style.css
> +
Don't add an extra line here.

2021-03-13 03:46 UTC, tmo66 commented on static/home/css/style.css
> +
Don't add an extra line here.

2021-03-13 03:46 UTC, tmo66 commented on static/home/css/style.css
> +	background-color:red;
Don't remove the spacing between both. It's how the code is formatted throughout the project.

2021-03-13 03:46 UTC, tmo66 commented on static/home/css/style.css
> -	/*margin: 5px 0;*/
Don't remove this.

2021-03-13 03:46 UTC, tmo66 commented on static/home/css/style.css
> -	/*padding: 0 5px;*/
Don't remove this.

2021-03-13 03:46 UTC, tmo66 commented on static/home/css/style.css
> +	/*box-sizing: border-box;*/
Don't delete anything which is not created by you. Just put them in the comment. And delete all those which are written by you but later on commented.

2021-03-13 03:50 UTC, tmo66 commented on static/home/css/style.css
> +	padding: 13.5px 11px;
Not sure about 13.5 px...it's too much!

2021-03-13 07:49 UTC, Kritikaagra commented
done with all necessary changes...
set all global variable as their previous values
remove all extra lines and comments added by me
also added lines I deleted ... and make them as comment to make changes

If I decrease padding from 13.5, the red colour on hover does not cover the whole space and leave a line at bottom.

2021-03-13 08:59 UTC, tmo66 requested changes
Just make these small changes, everything else looks good to me! And also after the commit squash all the commits in one.

2021-03-13 08:59 UTC, tmo66 commented on static/home/css/style.css
> +	padding: 0px 0px;
No need to write this..

2021-03-13 08:59 UTC, tmo66 commented on static/home/css/style.css
> -	padding: 3px 12px;
Don't remove these two-line, just put them in comment.

2021-03-13 08:59 UTC, tmo66 commented on static/home/css/style.css
> +	background: white;
No need to make changes here, as this whole part is already commented out.

2021-03-13 08:59 UTC, tmo66 commented on static/home/css/style.css
> +.navbar2 a:hover{
Don't make these changes, for now, we are handling navbar2 in a different issue.

2021-03-13 09:01 UTC, tmo66 commented
To squash your commits, follow these instructions:
* `git rebase -i HEAD~<no. of commits you made in total>`
* Except for first `pick`, replace all `pick` with `squash` in the file opened.
* Close the file after saving it.
* In the new file opened, remove all commit messages and write a new one and then close this file too after saving.
* Force push your changes. (`git push origin +<your-branch-name>`).

2021-03-16 19:17 UTC, garg3133 commented
Thank you @Kritikaagra for working on this. The enhancements were good but the navbar was not being displayed properly on small screens due to which I was reluctant to merge this PR. But then I thought, why not rebuild the entire navbar from scratch as it was very badly implemented (you must have seen there were two navbars, one for small screens and the other of larger screens). So, I spent some time on it and re-built it.

But, as your enhancements were good and I've taken some idea from this PR itself while rebuilding it, I'm still merging this PR so that you get your points for GSSoC. And I'm really sorry you didn't get your changes in the master branch. Hope you'll understand and continue making your amazing contributions. Thanks!

2021-03-16 19:18 UTC, garg3133 commented
Also, you should never make any changes directly into the master branch.

2021-03-16 19:19 UTC, merged

2021-03-17 02:03 UTC, Kritikaagra commented
Thank you @garg3133
And sorry for making changes in the master branch. I will take care this next time.